#!/usr/bin/env php
<?php

require_once __DIR__.'/../vendor/autoload.php';

use Symfony\Component\Console\Application;

$app = new Application('api translator', '0.1 ');
$app->add(new ApiTranslator\TranslateCommand());
$app->run();
